# Generated by Django 3.0.2 on 2020-01-19 06:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='Good news!!', max_length=200)),
                ('template', models.TextField(blank=True, default='', null=True)),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('sent', models.IntegerField(blank=True, default=0)),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, null=True), default=list, size=20)),
            ],
        ),
    ]
