# Generated by Django 3.0.2 on 2020-01-19 22:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, null=True, upload_to='templates')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('context', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, null=True), default=list, size=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='template',
        ),
    ]
