# Generated by Django 3.0.2 on 2020-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='file',
        ),
        migrations.AddField(
            model_name='template',
            name='file_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
