# Generated by Django 3.0.2 on 2020-01-24 02:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200122_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, null=True), default=list, size=30),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
